version: '3.8'

services:
  database:
    build:
      context: ./database
    container_name: agndb-database-dev
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=agndb
      - MYSQL_USER=agndb_user
      - MYSQL_PASSWORD=agndb_password
      - GENERATE_LARGE_DATASET=false
    volumes:
      - agndb-data-dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uagndb_user", "-pagndb_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: agndb-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=agndb_user
      - DB_PASSWORD=agndb_password
      - DB_NAME=agndb
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app
      - backend-logs-dev:/app/logs
    depends_on:
      database:
        condition: service_healthy
    # Enable hot-reload with uvicorn
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    image: node:20-alpine
    container_name: agndb-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1

volumes:
  agndb-data-dev:
  backend-logs-dev: 